SELECT HASHBYTES('SHA1', CONCAT('ORG_CASE:', [ORG_CASE].[id], 'ORG_UM_CASE:', [ORG_UM_CASE].[case_id],
'ORG_UM_LOS:', [ORG_UM_LOS].[id], 'ORG_UM_LOS_EXTENSION:', [ORG_UM_LOS_EXTENSION].[id])) [AUTH_LN_HASH],
[ORG_UM_CASE].[case_id] [CASE_ID],
[ORG_CASE].[id], [ORG_CASE].[TZIX_ID] [AUTH_ID],
[ORG_UM_LOS].[req_prov_id] [LOS_REQUESTING_PROVIDER],
ISNULL(CONVERT(VARCHAR, [ORG_CASE].CREATE_DATE, 112), 0) [HRD_INPUT_DT]
INTO ##Temp2 FROM [CAE_OLTP].[dbo].[ORG_CASE]
JOIN [CAE_OLTP].[dbo].[ORG_UM_CASE] ON [ORG_UM_CASE].[case_id] = [ORG_CASE].[id]	
JOIN [CAE_OLTP].[dbo].[ORG_UM_LOS] ON [ORG_CASE].[id] = [ORG_UM_CASE].[case_id]
LEFT JOIN [CAE_OLTP].[dbo].[ORG_UM_LOS_EXTENSION] ON [ORG_UM_LOS_EXTENSION].[LOS_ID] = [ORG_UM_LOS].[ID]